In [76]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [77]:
#Load the data set
data = sns.load_dataset("iris")
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [78]:
#Prepare the training set

# X = feature values, all the columns except the last column
X = data.iloc[:, :-1]

# y = target values, last column of the data frame
y = data.iloc[:, -1]

In [79]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [80]:
#Train the model
model = LogisticRegression()
model.fit(x_train, y_train) #Training the model

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()

In [81]:
#Test the model
predictions = model.predict(x_test)

In [82]:
x_test["prediction"] = predictions
x_test.head()

     sepal_length  sepal_width  petal_length  petal_width  prediction
73            6.1          2.8           4.7          1.2  versicolor
18            5.7          3.8           1.7          0.3      setosa
118           7.7          2.6           6.9          2.3   virginica
78            6.0          2.9           4.5          1.5  versicolor
76            6.8          2.8           4.8          1.4  versicolor

In [86]:
y_test = pd.DataFrame(y_test)
y_test.head()

        species
73   versicolor
18       setosa
118   virginica
78   versicolor
76   versicolor

In [91]:
x_test["real"] = y_test["species"]
x_test.head(10)

,sepal_length,sepal_width,petal_length,petal_width,prediction,real
73,6.1,2.8,4.7,1.2,versicolor,versicolor
18,5.7,3.8,1.7,0.3,setosa,setosa
118,7.7,2.6,6.9,2.3,virginica,virginica
78,6.0,2.9,4.5,1.5,versicolor,versicolor
76,6.8,2.8,4.8,1.4,versicolor,versicolor
31,5.4,3.4,1.5,0.4,setosa,setosa
64,5.6,2.9,3.6,1.3,versicolor,versicolor
141,6.9,3.1,5.1,2.3,virginica,virginica
68,6.2,2.2,4.5,1.5,versicolor,versicolor
82,5.8,2.7,3.9,1.2,versicolor,versicolor